[package]
name = "convert_number"
version = "0.1.0"
authors = ["David Cadena <david.cadena@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.123"
actix-web = "3.3.2"